name 'pi2'
maintainer 'Dayne Broderson'
maintainer_email 'broderosn@gmail.com'
license 'MIT'
description 'Installs/Configures pi2-cookbook'
long_description 'Installs/Configures pi2-cookbook'
version '0.1.1'

depends 'line', '~> 0.6.1'
depends 'apt', '~> 2.7.0'
depends 'chef-sugar', '~> 3.1.0'
depends 'packages', '~> 0.4.0'
